export const products = [
  {
    id: 1,
    name: 'Pembersih Serbaguna Super',
    description: 'Cairan pembersih ampuh untuk segala permukaan. Menghilangkan noda membandel dan memberikan aroma segar.',
    price: 55000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Cairan Pembersih',
  },
  {
    id: 2,
    name: 'Spons Mikrofiber Premium',
    description: 'Spons dengan daya serap tinggi untuk membersihkan debu dan kotoran tanpa meninggalkan goresan.',
    price: 25000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Alat Kebersihan',
  },
  {
    id: 3,
    name: 'Pengharum Ruangan Otomatis',
    description: 'Memberikan keharuman yang tahan lama untuk ruangan Anda. Dilengkapi dengan timer otomatis.',
    price: 120000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Pengharum Ruangan',
  },
  {
    id: 4,
    name: 'Sarung Tangan Karet Pelindung',
    description: 'Lindungi tangan Anda saat membersihkan. Terbuat dari bahan karet berkualitas yang tahan lama.',
    price: 15000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Alat Kebersihan',
  },
  {
    id: 5,
    name: 'Pembersih Kaca Anti-Jamur',
    description: 'Membersihkan kaca dan cermin hingga bening berkilau. Mencegah tumbuhnya jamur.',
    price: 45000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Cairan Pembersih',
  },
  {
    id: 6,
    name: 'Sikat Elektrik Multifungsi',
    description: 'Sikat elektrik dengan berbagai kepala sikat untuk membersihkan sudut yang sulit dijangkau.',
    price: 250000,
    imageUrl: '/images/product-placeholder.jpg',
    category: 'Alat Kebersihan',
  },
];
